runtime: python39
entrypoint: uwsgi --http-socket :$8080 --wsgi-file app.py --callable app --master --processes 1 --threads 2
runtime: python312

instance_class: F2

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
